apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-config
data:
  DB_HOST: "production-mysql-db.cqj026m4mlb9.us-east-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "production_db"
  REACT_APP_API_URL: https://bankapi.pod8medicare.online
